### ISSUE TITLE
Examples panic when minimized on Windows 10

### ISSUE THREAD

**Issue by EnergeticBark** [parasyte/pixels#157]
I've tried running each of the examples bundled with pixels and they all produce the same error when minimized:
```thread 'main' panicked at 'Error in Device::create_swap_chain: Both `SwapChain` width and height must be non-zero. Wait to recreate the `SwapChain` until the window has non-zero area.', C:\Users\Seth\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.7.1\src\backend\direct.rs:129:9```

Full backtrace:
```
thread 'main' panicked at 'Error in Device::create_swap_chain: Both `SwapChain` width and height must be non-zero. Wait to recreate the `SwapChain` until the window has non-zero area.', C:\Users\Seth\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.7.1\src\backend\direct.rs:129:9
stack backtrace:
   0:     0x7ff7edc56b0e - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7edc56b0e - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7edc56b0e - std::sys_common::backtrace::_print_fmt
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff7edc56b0e - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff7edc6d34b - core::fmt::write
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\fmt\mod.rs:1096
   5:     0x7ff7edc53b78 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\io\mod.rs:1568
   6:     0x7ff7edc598fd - std::sys_common::backtrace::_print
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff7edc598fd - std::sys_common::backtrace::print
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff7edc598fd - std::panicking::default_hook::{{closure}}
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:208
   9:     0x7ff7edc593c9 - std::panicking::default_hook
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:225
  10:     0x7ff7edc5a1b0 - std::panicking::rust_panic_with_hook
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:591
  11:     0x7ff7edc59ce1 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:497
  12:     0x7ff7edc5749f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:141
  13:     0x7ff7edc59c39 - std::panicking::begin_panic_handler
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:493
  14:     0x7ff7edc59bec - std::panicking::begin_panic_fmt
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:435
  15:     0x7ff7ed89c18c - wgpu::backend::direct::Context::handle_error_fatal::hb2d5066dfe28ddf2
  16:     0x7ff7ed89c6e3 - <wgpu::backend::direct::Context as wgpu::Context>::device_create_swap_chain::h37ac6e79b9ba80d9
  17:     0x7ff7ed894c3a - wgpu::Device::create_swap_chain::h4c8866c2b80a6d9f
  18:     0x7ff7ed7d5bbc - pixels::Pixels::resize_surface::hd6d14996845472fa
  19:     0x7ff7ed71d3c9 - winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}::h24e8eb318c1e3c72
  20:     0x7ff7ed7ba0b1 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::heb9489e1051104ce
  21:     0x7ff7ed7bd9c5 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::send_event::hbe9c88a1c97ac52d
  22:     0x7ff7ed7be174 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::move_state_to::h96b8a38b815150c0
  23:     0x7ff7ed7b97a1 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd94f7b92b2422110
  24:     0x7ff7ed7bcd78 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::catch_unwind::h24c223cef81085d3
  25:     0x7ff7ed7b469d - winit::platform_impl::platform::event_loop::process_control_flow::hb0cdcd332de198ef
  26:     0x7ffb17e4d3b6 - DefSubclassProc
  27:     0x7ffb17e4d26c - DefSubclassProc
  28:     0x7ffb24e6e858 - CallWindowProcW
  29:     0x7ffb24e6e3dc - DispatchMessageW
  30:     0x7ffb24e80bc3 - SendMessageTimeoutW
  31:     0x7ffb25cb0b54 - KiUserCallbackDispatcher
  32:     0x7ffb23841704 - NtUserDispatchMessage
  33:     0x7ffb24e6e2ea - DispatchMessageW
  34:     0x7ff7ed69a644 - winit::platform_impl::platform::event_loop::subclass_window::h59afd6603908d690
  35:     0x7ff7ed69a3e2 - alloc::alloc::box_free::h3181087947ca1779
  36:     0x7ff7ed69d8d6 - pollster::block_on::heb2150f9786b7aa8
  37:     0x7ff7ed725f86 - std::sys_common::backtrace::__rust_end_short_backtrace::h50ab36a2c944660f
  38:     0x7ff7ed725f9c - std::rt::lang_start::{{closure}}::hbd24e33f8f6a4dbe
  39:     0x7ff7edc5a487 - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\core\src\ops\function.rs:280
  40:     0x7ff7edc5a487 - std::panicking::try::do_call
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:379
  41:     0x7ff7edc5a487 - std::panicking::try
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:343
  42:     0x7ff7edc5a487 - std::panic::catch_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panic.rs:431
  43:     0x7ff7edc5a487 - std::rt::lang_start_internal
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\rt.rs:51
  44:     0x7ff7ed69eb37 - main
  45:     0x7ff7edd2f750 - invoke_main
                               at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  46:     0x7ff7edd2f750 - __scrt_common_main_seh
                               at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  47:     0x7ffb240e7034 - BaseThreadInitThunk
  48:     0x7ffb25c62651 - RtlUserThreadStart
error: process didn't exit successfully: `target\release\invaders.exe` (exit code: 101)
```

**Comment by parasyte** [comment]
This is something to do with `winit`. The stack trace points to https://github.com/parasyte/pixels/blob/9bfed17a7f51733f9042b3b524405229c628003b/examples/minimal-winit/src/main.rs#L67-L70

We could always add another condition to prevent passing zero as width or height, but IMHO this code should not be getting zeroes. Do you know if `winit` is normally supposed to provide zeroes to the resize event? I'm not sure why it would do that instead of giving a separate event for minimizing.

The two resize methods don't do input validation, so maybe that's also an improvement we should make. The only real input validation is just assertions around creating the resources, like this one: https://github.com/parasyte/pixels/blob/9bfed17a7f51733f9042b3b524405229c628003b/src/builder.rs#L40-L49

These resize methods can return `Result<(), T>` for this case, but there is really no way to handle the error. Another option is just no-op when either dimension is zero, but that seems kind of unexpected.

**Comment by parasyte** [comment]
Thanks for the additional context. That was roughly my conclusion as well.

**Comment by parasyte** [comment]
@EnergeticBark I have an open PR for fixing this in some cases. It doesn't work in all cases (as illustrated by the `imgui-winit` example, for reasons described above and in the commit messages. But I think that's about all I can do with this one! I'll gladly accept any feedback you might like to provide.
